server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CarolSTrindade/config-server
          default-label: main
          search-paths:
          - 'config*'